name: CI

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build backend
        run: ./gradlew compileKotlinBackend

      - name: Build frontend
        run: ./gradlew compileKotlinFrontend

      - name: Build electron
        run: ./gradlew buildApp

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: electron-build
          path: build/js/packages/StructuredDataEditor-electron

      - name: Test
        run: ./gradlew check
