name: CI

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test
        run: |
          ./gradlew compileKotlinBackend
          ./gradlew compileKotlinFrontend
          ./gradlew buildApp

      - name: Test
        run: ./gradlew check
